$schema: https://json-schema.org/draft/2020-12/schema
$id: https://schema.JsonSchema42.org/jns42-intermediate-a/schema

title: JsonSchema42 intermediate schema
type:
  - object
examples:
  - $schema: https://schema.JsonSchema42.org/jns42-intermediate-a/schema
    nodes:
      file:///simple-object.json:
        deprecated: false
        title: ""
        description: A very simple object
        examples: []
        types:
          - type: interface
            requiredProperties:
              - id
            propertyTypeNodeIds:
              id: file:///simple-object.json#/properties/id
              name: file:///simple-object.json#/properties/name
        compounds: []
      file:///simple-object.json#/properties/id:
        deprecated: false
        title: ""
        description: An identity
        examples: []
        types:
          - type: number
            numberType: integer
            minimumExclusive: 0
        compounds: []
      file:///simple-object.json#/properties/name:
        deprecated: false
        title: ""
        description: A name
        examples: []
        types:
          - type: string
            minimumLength: 2
            maximumLength: 20
        compounds: []
required:
  - nodes
properties:
  $schema:
    type: string
    const: https://schema.JsonSchema42.org/jns42-intermediate-a/schema
  nodes:
    type: object
    additionalProperties: { $ref: "#/$defs/node" }

$defs:
  node:
    type:
      - object
    required:
      - deprecated
      - title
      - description
      - examples
      - types
      - compounds
    properties:
      superNodeId:
        type: string
      deprecated:
        type: boolean
      title:
        type: string
      description:
        type: string
      examples:
        type: array
        items: true
      types:
        type: array
        items: { $ref: "#/$defs/type-union" }
      compounds:
        type: array
        items: { $ref: "#/$defs/compound-union" }
  
  type-union:
    oneOf:
      - $ref: "#/$defs/null-type"
      - $ref: "#/$defs/any-type"
      - $ref: "#/$defs/never-type"
      - $ref: "#/$defs/boolean-type"
      - $ref: "#/$defs/number-type"
      - $ref: "#/$defs/string-type"
      - $ref: "#/$defs/tuple-type"
      - $ref: "#/$defs/array-type"
      - $ref: "#/$defs/interface-type"
      - $ref: "#/$defs/record-type"
  
  compound-union:
    oneOf:
      - $ref: "#/$defs/one-of-compound"
      - $ref: "#/$defs/any-of-compound"
      - $ref: "#/$defs/all-of-compound"
  
  null-type:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        const: "null"
  
  any-type:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        const: any
  
  never-type:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        const: never
  
  boolean-type:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        const: boolean
      options:
        type: array
        items:
          type: boolean
  
  number-type:
    type: object
    required:
      - type
      - numberType
    properties:
      type:
        type: string
        const: number
      numberType:
        type: string
        enum:
          - integer
          - float
      options:
        type: array
        items:
          type: number
      minimumInclusive:
        type: number
      minimumExclusive:
        type: number
      maximumInclusive:
        type: number
      maximumExclusive:
        type: number
      multipleOf:
        type: number
  
  string-type:
    type: object
    required:
      - type
    properties:
      type:
        type: string
        const: string
      options:
        type: array
        items:
          type: string
      minimumLength:
        type: number
      maximumLength:
        type: number
      valuePattern:
        type: string
  
  tuple-type:
    type: object
    required:
      - type
      - itemTypeNodeIds
    properties:
      type:
        type: string
        const: tuple
      itemTypeNodeIds:
        type: array
        items:
          type: string
  
  array-type:
    type: object
    required:
      - type
      - itemTypeNodeId
    properties:
      type:
        type: string
        const: array
      minimumItems:
        type: number
      maximumItems:
        type: number
      uniqueItems:
        type: boolean
      itemTypeNodeId:
        type: string
  
  interface-type:
    type: object
    required:
      - type
      - requiredProperties
      - propertyTypeNodeIds
    properties:
      type:
        type: string
        const: interface
      requiredProperties:
        type: array
        items:
          type: string
      propertyTypeNodeIds:
        type: object
        additionalProperties:
          type: string
  
  record-type:
    type: object
    required:
      - type
      - requiredProperties
      - propertyTypeNodeId
    properties:
      type:
        type: string
        const: record
      requiredProperties:
        type: array
        items:
          type: string
      minimumProperties:
        type: number
      maximumProperties:
        type: number
      propertyTypeNodeId:
        type: string
  
  one-of-compound:
    type: object
    required:
      - type
      - typeNodeIds
    properties:
      type:
        type: string
        const: one-of
      typeNodeIds:
        type: array
        items:
          type: string
  
  any-of-compound:
    type: object
    required:
      - type
      - typeNodeIds
    properties:
      type:
        type: string
        const: any-of
      typeNodeIds:
        type: array
        items:
          type: string
  
  all-of-compound:
    type: object
    required:
      - type
      - typeNodeIds
    properties:
      type:
        type: string
        const: all-of
      typeNodeIds:
        type: array
        items:
          type: string
